name: CI-Lint

on: [push, pull_request]

jobs:

  code-quality-ruff:

    defaults:
      run:
        shell: bash

    runs-on: ubuntu-latest

    name: Ruff

    steps:
      - name: Check out source repository
        uses: actions/checkout@v6
      - name: Set up Python environment
        uses: actions/setup-python@v7
        with:
          python-version: "3.14"
      - name: Install pyproject.toml dependencies
        run: |
          if [ -f "pyproject.toml" ]; then pip install uv && uv sync --extra dev; fi
      - name: Analysing the code with ruff
        run: |
          uv run ruff check .

  code-quality-pylint:
    runs-on: ubuntu-latest
    name: Pylint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v6
      - name: Set up Python environment
        uses: actions/setup-python@v7
        with:
          python-version: "3.14"
      - name: Install pyproject.toml dependencies
        run: |
          if [ -f "pyproject.toml" ]; then pip install uv && uv sync --extra dev; fi
      - name: Analysing the code with pylint
        run: |
          uv run pylint $(git ls-files '*.py')
