name: CI-Security

on: [push, pull_request]

jobs:
  file-security-scan:
      runs-on: ubuntu-latest
      name: UV-Secure Scan
      steps:
        - name: Check out source repository
          uses: actions/checkout@v6

        - name: Install the latest version of uv and set the python version
          uses: astral-sh/setup-uv@v10.0.1
          with:
            python-version: "3.14"

        - name: Install uv-secure
          run: uv tool install uv-secure

        - name: Scan for vulnerabilities (High + Critical)
          run: uv-secure --format json --severity high
