name: CI-Security

on: [push, pull_request]

jobs:
  file-security-scan:
      runs-on: ubuntu-latest
      name: Filesystem Scan
      steps:
        - name: Check out source repository
          uses: actions/checkout@v6
